package com.bilgeadam;

import java.io.FileOutputStream;

import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;

public class ITextExample {

	private final String FONT = "/System/Library/Fonts/Supplemental/Arial Unicode.ttf";
	private Document pdf;
	private Font font;

	public static void main(String[] args) {

		ITextExample iText = new ITextExample();
		try {

			iText.createPDDFile();
			iText.pdf.open();
			iText.createPDF();
			iText.pdf.close();

		} catch (Exception e) {

			e.printStackTrace();
		}
	}

	private void createPDF() throws DocumentException {
		this.pdf.add(new Paragraph("Automatically generated by a program using the IText package" + this.getFont()));
	}

	private void createPDDFile() throws Exception {
		this.pdf = new Document(PageSize.A4, 20, 20, 20, 20);

		FileOutputStream fos = new FileOutputStream(
				"C:\\Users\\semih\\Desktop\\eclipse-workspace\\PDF-Excel\\ITextExample.pdf");
		PdfWriter.getInstance(this.pdf, fos);

	}

	private Font getFont() {
		if (this.font == null) {
			this.font = FontFactory.getFont(FONT);
		}
		return this.font;
	}

}
